"""SOLVE-IT Digital Forensics Knowledge Base and Ontology — solveit-analysis module."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ForensicToolTagBasedReport:
    """A report generated by a forensic tool based on tags added during analysis."""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/ForensicToolTagBasedReport"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class Hypothesis:
    """A proposition or explanation put forward for consideration during forensic analysis, which may be supported or contradicted by observable artifacts."""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/Hypothesis"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class HypothesisSet:
    """A collection of competing alternative hypotheses considered together, for example the mutually exclusive explanations proposed for a single observation. Members are linked with solveit-analysis:hasHyp"""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/HypothesisSet"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class HypothesisedCommunication:
    """A communication that is hypothesised to have occurred between parties, potentially inferred from partial message records, contact patterns, or metadata fragments. Use uco-observable:from and uco-obser"""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/HypothesisedCommunication"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class HypothesisedDevice:
    """A device that is hypothesised to have been involved, such as a device inferred from artifacts but not yet physically identified or examined."""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/HypothesisedDevice"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class HypothesisedEvent:
    """An event that is hypothesised to have occurred."""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/HypothesisedEvent"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class HypothesisedRelationship:
    """A relationship between entities that is hypothesised to exist, such as an inferred association between persons, accounts, devices, or locations based on co-occurrence patterns, shared identifiers, or """

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/HypothesisedRelationship"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class HypothesisedUserAccount:
    """A user account that is hypothesised to have existed, for example inferred from recovered deleted account records, carved registry artifacts, or references to the account in other artifacts. Supporting"""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/HypothesisedUserAccount"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)


@dataclass
class HypothesisedWebSearch:
    """A web search that is hypothesised to have been performed, potentially inferred from browser history fragments, cached results, or suggested search terms. Use uco-observable:keywordSearchTerm for the s"""

    CLASS_IRI: str = "https://ontology.solveit-df.org/solveit/analysis/HypothesisedWebSearch"
    created_by: Optional[IdentityAbstraction] = field(default=None)
    description: list[str] = field(default_factory=list)
    external_reference: list[ExternalReference] = field(default_factory=list)
    has_facet: list[Facet] = field(default_factory=list)
    modified_time: list[datetime] = field(default_factory=list)
    name: Optional[str] = field(default=None)
    object_created_time: Optional[datetime] = field(default=None)
    object_marking: list[MarkingDefinitionAbstraction] = field(default_factory=list)
    object_status: Optional[str] = field(default=None)
    spec_version: Optional[str] = field(default=None)
    tag: list[str] = field(default_factory=list)
    statement: list[str] = field(default_factory=list)

