"""CAC Ontology - Crimes Against Children — CASE/UCO SDK extension bindings."""

__version__ = "3.0.0"

NAMESPACES: dict[str, str] = {
    "cac-core": "https://cacontology.projectvic.org/core#",
    "cacontology": "https://cacontology.projectvic.org#",
    "cacontology-ai-csam": "https://cacontology.projectvic.org/ai-csam#",
    "cacontology-analyst-wellbeing": "https://cacontology.projectvic.org/analyst-wellbeing#",
    "cacontology-asset-forfeiture": "https://cacontology.projectvic.org/asset-forfeiture#",
    "cacontology-athletic-exploitation": "https://cacontology.projectvic.org/athletic#",
    "cacontology-bridge-case": "https://cacontology.projectvic.org/bridge/case#",
    "cacontology-bridge-gufo": "https://cacontology.projectvic.org/bridge/gufo#",
    "cacontology-bridge-uco": "https://cacontology.projectvic.org/bridge/uco#",
    "cacontology-case-management": "https://cacontology.projectvic.org/case-management#",
    "cacontology-custodial": "https://cacontology.projectvic.org/custodial#",
    "cacontology-detection": "https://cacontology.projectvic.org/detection#",
    "cacontology-educational-exploitation": "https://cacontology.projectvic.org/educational#",
    "cacontology-extremist-enterprises": "https://cacontology.projectvic.org/extremist-enterprises#",
    "cacontology-forensics": "https://cacontology.projectvic.org/forensics#",
    "cacontology-grooming": "https://cacontology.projectvic.org/grooming#",
    "cacontology-hotlines": "https://cacontology.projectvic.org/hotlines#",
    "cacontology-institutional-exploitation": "https://cacontology.projectvic.org/institutional-exploitation#",
    "cacontology-integration-patterns": "https://cacontology.projectvic.org/integration-patterns#",
    "cacontology-international": "https://cacontology.projectvic.org/international#",
    "cacontology-investigation-coordination": "https://cacontology.projectvic.org/investigation-coordination#",
    "cacontology-law-enforcement-corruption": "https://cacontology.projectvic.org/law-enforcement-corruption#",
    "cacontology-legal-harmonization": "https://cacontology.projectvic.org/legal-harmonization#",
    "cacontology-legal-outcomes": "https://cacontology.projectvic.org/legal-outcomes#",
    "cacontology-multi-jurisdiction": "https://cacontology.projectvic.org/multi-jurisdiction#",
    "cacontology-partnerships": "https://cacontology.projectvic.org/partnerships#",
    "cacontology-physical-evidence": "https://cacontology.projectvic.org/physical#",
    "cacontology-platform-infrastructure": "https://cacontology.projectvic.org/infrastructure#",
    "cacontology-platforms": "https://cacontology.projectvic.org/platforms#",
    "cacontology-prevention": "https://cacontology.projectvic.org/prevention#",
    "cacontology-production": "https://cacontology.projectvic.org/production#",
    "cacontology-recantation": "https://cacontology.projectvic.org/recantation#",
    "cacontology-recruitment-networks": "https://cacontology.projectvic.org/recruitment-networks#",
    "cacontology-sadistic-online-exploitation": "https://cacontology.projectvic.org/soe#",
    "cacontology-sex-offender-registry": "https://cacontology.projectvic.org/sex-offender-registry#",
    "cacontology-sex-trafficking": "https://cacontology.projectvic.org/trafficking#",
    "cacontology-sextortion": "https://cacontology.projectvic.org/sextortion#",
    "cacontology-specialized-units": "https://cacontology.projectvic.org/specialized-units#",
    "cacontology-stranger-abduction": "https://cacontology.projectvic.org/abduction#",
    "cacontology-street-recruitment": "https://cacontology.projectvic.org/street#",
    "cacontology-synthesis": "https://cacontology.projectvic.org/synthesis#",
    "cacontology-tactical": "https://cacontology.projectvic.org/tactical#",
    "cacontology-taskforce": "https://cacontology.projectvic.org/taskforce#",
    "cacontology-temporal": "https://cacontology.projectvic.org/temporal#",
    "cacontology-training": "https://cacontology.projectvic.org/training#",
    "cacontology-undercover": "https://cacontology.projectvic.org/undercover#",
    "cacontology-us-ncmec": "https://cacontology.projectvic.org/us/ncmec#",
    "cacontology-usa-federal-law": "https://cacontology.projectvic.org/usa-federal-law#",
    "cacontology-usa-legislative": "https://cacontology.projectvic.org/usa-legislative#",
    "cacontology-victim-impact": "https://cacontology.projectvic.org/victim-impact#",
}

REGISTRY_PATH = __file__.replace("__init__.py", "_registry.json")
